services:
  mlflow:
    image: python:3.10-slim
    command: >
      bash -c "pip install mlflow && mlflow server
      --backend-store-uri sqlite:///mlruns/mlflow.db
      --default-artifact-root /mlartifacts
      --host 0.0.0.0 --port 5001"
    ports:
      - "5001:5001"
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts

  fraud-api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5001

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/alert_rules.yml:/etc/prometheus/alert_rules.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
